-- Picker
-- Author: JTF
-- DateCreated: 12/18/2020 2:02:37 PM
--------------------------------------------------------------






INSERT INTO CityStates (CivilizationType, CityStateCategory, Name, Icon, Bonus)
VALUES ('JTF_CIVILIZATION_REGENSBURG', 'TRADE', 'LOC_JTF_CIVILIZATION_REGENSBURG_NAME', 'ICON_JTF_CIVILIZATION_REGENSBURG', 'LOC_JTF_LEADER_TRAIT_REGENSBURG_DESCRIPTION1');



INSERT INTO CityStates (Domain, CivilizationType, CityStateCategory, Name, Icon, Bonus)
VALUES ('Expansion1CityStates', 'JTF_CIVILIZATION_REGENSBURG', 'TRADE', 'LOC_JTF_CIVILIZATION_REGENSBURG_NAME', 'ICON_JTF_CIVILIZATION_REGENSBURG', 'LOC_JTF_LEADER_TRAIT_REGENSBURG_DESCRIPTION1');


INSERT INTO CityStates (Domain, CivilizationType, CityStateCategory, Name, Icon, Bonus)
VALUES ('Expansion2CityStates', 'JTF_CIVILIZATION_REGENSBURG', 'TRADE', 'LOC_JTF_CIVILIZATION_REGENSBURG_NAME', 'ICON_JTF_CIVILIZATION_REGENSBURG', 'LOC_JTF_LEADER_TRAIT_REGENSBURG_DESCRIPTION1');
