
--------------------------------------------------------------

--=====
--TYPES
--=====
INSERT INTO Types (Type, Kind)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA',							'KIND_CIVILIZATION'),
		('JTF_LEADER_MINOR_CIV_LJUBLJANA',						'KIND_LEADER'),
		('JTF_MODIFIER_LJUBLJANA_DISTRICTS',					'KIND_MODIFIER'),
		('JTF_MINOR_CIV_LJUBLJANA_TRAIT',						'KIND_TRAIT');

--===============
--TYPE PROPERTIES
--===============
INSERT INTO TypeProperties (Type, Name, Value)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA', 'CityStateCategory', 'CULTURAL');

--=============
--CIVILIZATIONS
--=============
INSERT INTO Civilizations (CivilizationType, Name, Description, Adjective, StartingCivilizationLevelType, RandomCityNameDepth, Ethnicity)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA', 'LOC_JTF_CIVILIZATION_LJUBLJANA_NAME', 'LOC_JTF_CIVILIZATION_LJUBLJANA_DESCRIPTION', 'LOC_JTF_CIVILIZATION_LJUBLJANA_ADJECTIVE', 'CIVILIZATION_LEVEL_CITY_STATE', 1, 'ETHNICITY_EURO'); 

--=======
--LEADERS
--=======
INSERT INTO CivilizationLeaders (CivilizationType, LeaderType, CapitalName)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA', 'JTF_LEADER_MINOR_CIV_LJUBLJANA', 'LOC_JTF_CITY_NAME_LJUBLJANA');

INSERT INTO Leaders (LeaderType, Name, InheritFrom)
	VALUES
		('JTF_LEADER_MINOR_CIV_LJUBLJANA', 'LOC_JTF_CIVILIZATION_LJUBLJANA_NAME', 'LEADER_MINOR_CIV_CULTURAL');

--======
--TRAITS
--======
INSERT INTO LeaderTraits (LeaderType, TraitType)
	VALUES
		('JTF_LEADER_MINOR_CIV_LJUBLJANA', 'JTF_MINOR_CIV_LJUBLJANA_TRAIT');

INSERT INTO Traits (TraitType, Name, Description)
	VALUES
		('JTF_MINOR_CIV_LJUBLJANA_TRAIT', 'LOC_JTF_LEADER_TRAIT_LJUBLJANA_NAME', 'LOC_JTF_LEADER_TRAIT_LJUBLJANA_DESCRIPTION');

--===============
--TRAIT MODIFIERS
--===============
INSERT INTO TraitModifiers (TraitType, ModifierId)
	VALUES
		('JTF_MINOR_CIV_LJUBLJANA_TRAIT', 'MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS');

--=========
--MODIFIERS
--=========
INSERT INTO Modifiers (ModifierId,						ModifierType,											SubjectRequirementSetId)	
	VALUES
		('MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS',					'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'PLAYER_IS_SUZERAIN'),
		('MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS_MODIFIER',			'JTF_MODIFIER_LJUBLJANA_DISTRICTS',						'DISTRICT_IS_THEATER');

INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
	VALUES
		('JTF_MODIFIER_LJUBLJANA_DISTRICTS', 'COLLECTION_PLAYER_DISTRICTS', 'EFFECT_ADJUST_DISTRICT_YIELD_MODIFIER');


--==================
--MODIFIER ARGUMENTS
--==================
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES
		('MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS',					'ModifierId',		'MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS_MODIFIER'),
		('MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS_MODIFIER',			'YieldType',		'YIELD_CULTURE'),
		('MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS_MODIFIER',			'DistrictType',		'DISTRICT_THEATER'),
		('MINOR_CIV_LJUBLJANA_THEATER_CULTURE_BONUS_MODIFIER',			'Amount',			'100');

--==========
--CITY NAMES
--==========		
INSERT INTO CityNames (CivilizationType, CityName)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA', 'LOC_JTF_CITY_NAME_LJUBLJANA');

--=============
--PLAYER COLORS
--=============
INSERT INTO PlayerColors (Type, Usage, PrimaryColor, SecondaryColor, TextColor)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA', 'Minor', 'COLOR_PLAYER_CITY_STATE_PRIMARY', 'COLOR_PLAYER_CITY_STATE_CULTURAL_SECONDARY', 'COLOR_PLAYER_CITY_STATE_CULTURAL_SECONDARY');

--============
--START BIASES
--============

		
INSERT INTO StartBiasTerrains (CivilizationType, TerrainType, Tier)
	VALUES
		('JTF_CIVILIZATION_LJUBLJANA', 'TERRAIN_PLAINS_HILLS', 1),
		('JTF_CIVILIZATION_LJUBLJANA', 'TERRAIN_GRASS_HILLS', 1),
		
		('JTF_CIVILIZATION_LJUBLJANA', 'TERRAIN_GRASS', 2),		
		('JTF_CIVILIZATION_LJUBLJANA', 'TERRAIN_PLAINS', 2);
